### ISSUE TITLE
mac os 安装报错

### ISSUE THREAD

**Issue by Osub** [BetterJS/badjs-installer#2]
```
========  badjs-acceptor ===========
(node:77048) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
[2016-12-30 18:13:37.746] [INFO] [default] - start badjs-accepter , listen 80 ...
(node:77052) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
[2016-12-30 18:13:37.748] [INFO] [default] - start badjs-accepter , listen 80 ...
(node:77049) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
[2016-12-30 18:13:37.751] [INFO] [default] - start badjs-accepter , listen 80 ...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: bind EACCES null:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at cb (net.js:1322:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
(node:77050) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: bind EACCES null:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at cb (net.js:1322:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
[2016-12-30 18:13:37.759] [INFO] [default] - start badjs-accepter , listen 80 ...
(node:77051) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: bind EACCES null:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at cb (net.js:1322:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: bind EACCES null:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at cb (net.js:1322:16)
    at rr (cluster.js:625:14)
    at Worker.<anonymous> (cluster.js:594:9)
    at process.<anonymous> (cluster.js:765:8)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)




========== badjs-mq =========
[2016-12-30 18:13:39.243] [INFO] [default] - start badjs-mq success.
(node:77054) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
[2016-12-30 18:13:39.465] [INFO] [default] - running in debug
connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead badjs-mq/node_modules/connect/lib/middleware/bodyParser.js:56:20
connect deprecated limit: Restrict request size at location of read badjs-mq/node_modules/connect/lib/middleware/multipart.js:86:15
(node:77055) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
[2016-12-30 18:13:39.563] [INFO] [default] - start openapi service , port:9500
connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead badjs-acceptor/node_modules/connect/lib/middleware/bodyParser.js:56:20
connect deprecated limit: Restrict request size at location of read badjs-acceptor/node_modules/connect/lib/middleware/multipart.js:86:15
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at Worker.send (cluster.js:64:28)
    at dispatchCluster (/Users/machero/badjs-installer/badjs-acceptor/service/ProjectService.js:20:25)
    at ProjectService (/Users/machero/badjs-installer/badjs-acceptor/service/ProjectService.js:54:5)
    at Timeout._onTimeout (/Users/machero/badjs-installer/badjs-acceptor/app.js:37:44)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)




========= badjs-storage ==========
[2016-12-30 18:13:41.403] [INFO] [default] - start badjs-storage success.
(node:77061) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
[2016-12-30 18:13:41.461] [INFO] [default] - Connected correctly to mongodb
[2016-12-30 18:13:41.535] [INFO] [default] - [77062] worker of  realTotal ready
[2016-12-30 18:13:42.511] [INFO] [default] - query server start ok , listen 9000
[2016-12-30 18:13:42.513] [INFO] [default] - 36000000s should clear
[2016-12-30 18:13:42.526] [INFO] [default] - Connected correctly to mongodb
[2016-12-30 18:13:42.527] [INFO] [default] - Connected correctly to server




========== badjs-web =========
[2016-12-30 18:13:43.224] [INFO] [default] - running in debug
express-session deprecated undefined resave option; provide resave option badjs-web/workflow/ExpressInitWorker.js:23:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option badjs-web/workflow/ExpressInitWorker.js:23:9
[2016-12-30 18:13:43.788] [INFO] [default] - connect mysql: mysql://root:root@localhost:3306/badjs
[2016-12-30 18:13:43.927] [INFO] [default] - starting mq ...
[2016-12-30 18:13:44.212] [INFO] [default] - create ProcessPool , number : 15
[2016-12-30 18:13:44.219] [INFO] [default] - start badjs-web , listen 8081 ...
(node:77064) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
/Users/machero/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/Parser.js:78
        throw err; // Rethrow non-MySQL errors
        ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
    at Handshake.Sequence._packetToError (/Users/machero/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/Users/machero/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:103:18)
    at Protocol._parsePacket (/Users/machero/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/machero/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/Users/machero/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/machero/badjs-installer/badjs-web/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (/Users/machero/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/Users/machero/badjs-installer/badjs-web/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/Users/machero/badjs-installer/badjs-web/node_modules/mysql/lib/Connection.js:136:18)
    at Driver.connect (/Users/machero/badjs-installer/badjs-web/node_modules/orm/lib/Drivers/DML/mysql.js:60:10)
    at Object.exports.connect (/Users/machero/badjs-installer/badjs-web/node_modules/orm/lib/ORM.js:128:10)
    at Object.module.exports (/Users/machero/badjs-installer/badjs-web/node_modules/orm/lib/Express.js:12:6)
    at Object.exports.express (/Users/machero/badjs-installer/badjs-web/node_modules/orm/lib/ORM.js:39:30)
    at Object.<anonymous> (/Users/machero/badjs-installer/badjs-web/workflow/ExpressInitWorker.js:35:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

```

**Comment by sm0king** [comment]
遇到几乎同样的问题，没找到原因

**Comment by loskael** [comment]
1. Mac 下默认不允许绑定到 80 端口
> Error: bind EACCES null:80

> Non-privileged user (not root) can’t open a listening socket on ports below 1024.

可以试试 `sudo`

2. mysql 连接不上
>Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)

**Comment by loskael** [comment]
多说一句，这个没必要在 mac 下部署，一般都是用 linux 做服务器部署的，在 mac 下部署没有意义，如果想调试且没有 linux 环境，可以尝试 docker 部署

**Comment by xiaoyanzheng** [comment]
docker 部署
运行   docker run -i -d -p 80:80 -p 8081:8081 docker.io/caihuijigood/badjs-docker bash badjs mysql=mysql://root:root@192.168.1.101:3306/badjs mongodb=mongodb://192.168.1.101:27017/badjs
这个命令也是报错

**Comment by catherine201** [comment]
query url : http://127.0.0.1:9000/query 报{"ok":false,"msg":"id is required"}
http://127.0.0.1:9000/errorMsgTop 报{"ok":false,"msg":""date error""}
internal/child_process.js:366
    throw errnoException(err, 'spawn');
    ^

Error: spawn Unknown system error -86
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:551:9)
    at Object.execFile (child_process.js:221:15)
    at ClientRequest.<anonymous> (/Users/catherine/Documents/one/badjs-installer/badjs-web/node_modules/node-highcharts-exporting/index.js:41:38)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
